name: cadiu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12
  - torchvision=0.13
  - cudatoolkit=11.3
  - numpy=1.21
  - scipy=1.7
  - scikit-learn=1.0
  - pandas=1.3
  - matplotlib=3.5
  - seaborn=0.11
  - plotly=5.5
  - einops=0.4
  - opencv=4.5
  - pyyaml=6.0
  - pip
  - pip:
    - torchinfo