# Dataset
data_root: "/home/phd/datasets/"
dataset: "visa"
task_type: "all"  # or specific category like "capsule"
input_size: [256, 256]
normalize_mean: [0.485, 0.456, 0.406]
normalize_std: [0.229, 0.224, 0.225]

# Training
batch_size: 4
num_workers: 4
device: "cuda:0"
task_id: "T1"
instruction: "T"  # 'R' or 'T'
task_stage: null  # For multi-stage, e.g., 1

# Model
dae:
  latent_dim_prim: 512
  latent_dim_sem: 256
  lambda_mi: 1.8
  gamma_smooth: 0.3

dpg:
  eta_fim: 1e-4
  stage_configs:  # Only if multi_stage: true
    - input_dim: 768
      hidden_dim: 512
      output_dim: 256
    - input_dim: 256
      hidden_dim: 128
      output_dim: 1

ssm:
  r: 64
  buffer_size: 50

# Logging
log_dir: "experiments/logs"
checkpoint_dir: "experiments/checkpoints"
multi_stage: false